### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Vitalasy** [Luna5ama/TrollHack#10]
https://paste.ee/p/k5EjC

**Comment by master7720** [comment]
get rid of baritone-api-forge-1.2.15 should work then

**Comment by master7720** [comment]
client already has baritone in it btw

**Comment by master7720** [comment]
btw stop using abyss cracked makes you look dumb

**Comment by Vitalasy** [comment]
> btw stop using abyss cracked makes you look dumb

lol i tried it ages ago it is just disabled in my mods folder

**Comment by Vitalasy** [comment]
> get rid of baritone-api-forge-1.2.15 should work then

https://paste.ee/p/y9PTa without the api

**Comment by master7720** [comment]
is there -noverify in your jvm

**Comment by Vitalasy** [comment]
> is there -noverify in your jvm

no.

**Comment by Vitalasy** [comment]
![image](https://user-images.githubusercontent.com/94053086/158049687-eea817f0-1258-4127-a128-459bd561cae9.png)

**Comment by Luna5ama** [comment]
There is a space in your path. Will fix later. Move it to somewhere else to run for now.

**Comment by Vitalasy** [comment]
> There is a space in your path. Will fix later. Move it to somewhere else to run for now.

java path or multi mc path.
