### ISSUE TITLE
how to turn off this?

### ISSUE THREAD

**Issue by AlsoShy** [Luna5ama/TrollHack#101]
![image](https://user-images.githubusercontent.com/120041780/235470068-cedafb43-f714-41e1-be4a-1ff39bfbe381.png)
this and 
this 
![image](https://user-images.githubusercontent.com/120041780/235470167-ea2419c7-85d7-48ea-a6d8-244e46f29cbc.png)

**Comment by AlsoShy** [comment]
I need to turn off spotted and some sort of idn chams?

**Comment by AlsoShy** [comment]
I only use future and troll hack with optifine

**Comment by Smug2f** [comment]
i know how to remove these
for 1st picture disable the module called visual range 
for 2nd picture there are 2 options 1 is to go to combat setting , r click it and go to render and disable cham , 2nd option is to go to zealot crystal+ , go to render and look if their are target chams and if yes watch below if it s called single or multi , if yes then set it to none and fixed

**Comment by AlsoShy** [comment]
thanks it worked
