### ISSUE TITLE
不完整方块像是完整方块一样

### ISSUE THREAD

**Issue by its-Hans** [Luna5ama/TrollHack#102]
比如半砖，栅栏，告示牌，雪啥的 告示牌后面明明有箱子 但是左右键都只能和告示牌交互
我尝试了禁用我的其他所有模组 以及删除trollhack/config/modules文件夹 但仍然没有作用
![selectionhighlight](https://user-images.githubusercontent.com/122334657/236425458-0bee60dc-a441-4069-8892-f8bd0bab569f.png)
![selectionhighlight 2](https://user-images.githubusercontent.com/122334657/236425467-b7285554-8e41-4296-9332-e2b26bb31372.png)
![交互](https://user-images.githubusercontent.com/122334657/236425473-31d74f31-1afe-45b1-9a4f-2c4ff231e17e.png)

**Comment by Luna5ama** [comment]
Temp workaround: hold alt while right-clicking. There will be a fix for this later.

**Comment by Luna5ama** [comment]
Fixed in 1ed0b028
