### ISSUE TITLE
从v1.1.0开始的鬼手模式bug！？

### ISSUE THREAD

**Issue by Ulinp** [Luna5ama/TrollHack#109]
说实话，v1,1,0以后的鬼手模式是不错的。但我提一个小小的建议，我希望添加回zc+原来的鬼手模式（mode：spoof）因为新的鬼手模式对于zc+来说并不能绕过国服和小宋。表现如下:只渲染要放的地方，但是手并没有任何动作，我的摇手模式是client，并且放置没有关。如果坐标离00越远，反而能放 越来越正常。

**Comment by Luna5ama** [comment]
把Place Switch Bypass改回None就是原来的Spoof

**Comment by Ulinp** [comment]
那么这可能是个bug，总是会看着水晶有放置位置渲染 而手却不摇晃
