### ISSUE TITLE
语言language

### ISSUE THREAD

**Issue by stelarvalley** [Luna5ama/TrollHack#111]
请问如何修改语言为中文？我点击language没有反应，还是英文。
How can I modify the language to Chinese? I didn't respond when I clicked on language, it's still in English.

**Comment by Smug2f** [comment]
go to troll gui go to language set override language to true and remove en_us by clicking the sup key or return one in your keyboard and enter instead of en_us , zh_cn and enter

**Comment by Smug2f** [comment]
![image](https://github.com/Luna5ama/TrollHack/assets/121037067/c362e393-d12e-4e7a-b22d-536c9c796b77)

**Comment by stelarvalley** [comment]
亲爱的作者，请问可以尽量用中文回答吗？我机翻没完全搞懂意思，像sup key按键在哪我就不知道，而且我按你第二张图操作改成zh-cn无反应，我的版本是最新版
Dear author, could you please try to answer in Chinese? I didn't fully understand the meaning of the machine translation. I don't know where the sup key button is, and I changed it to zh cn according to your second image without any response. My version is the latest version

**Comment by stelarvalley** [comment]
![e3cd9d2f7b71d24acb3962a7ee6e69e](https://github.com/Luna5ama/TrollHack/assets/125882041/d548309e-0ba5-4a90-b8bf-cbf01b9c99f1)

**Comment by Smug2f** [comment]
按回车键，完成
press enter and done
