### ISSUE TITLE
win7与win10无法正常启动trollhack

### ISSUE THREAD

**Issue by amanjun1337** [Luna5ama/TrollHack#118]
版本都是1.20 dc群下的nightly版本 win7是GT730 I5 4代  win10是I5 4代 GT950M             以下是游戏导出的log日志
[latest（win7）.log](https://github.com/Luna5ama/TrollHack/files/11958365/latest.win7.log)
[latest（win10）.log](https://github.com/Luna5ama/TrollHack/files/11958367/latest.win10.log)

**Comment by Luna5ama** [comment]
Update your graphics drivers. Make sure the laptop is set to use discrete graphics.
