### ISSUE TITLE
Gradle出现问题,dev.luna5ama.jar-optimizer 找不到

### ISSUE THREAD

**Issue by IDhammaI** [Luna5ama/TrollHack#120]
![Snipaste_2023-07-07_12-57-04](https://github.com/Luna5ama/TrollHack/assets/124808841/7b77415d-5917-417c-8944-24daa55a47a1)

**Comment by Smug2f** [comment]
代码是用kotlin写的，不是用gradlew写的，你需要用java 17来构建客户端。
