### ISSUE TITLE
gradle失败，原因是fastmc这个插件无法找到，应该是项目的问题[我问了好几个朋友都是同样情况qaq]

### ISSUE THREAD

**Issue by IDhammaI** [Luna5ama/TrollHack#121]
![V K{VA7ABT9`6Z(`I4P)@IT](https://github.com/Luna5ama/TrollHack/assets/124808841/c43ce5ef-0d8c-4f9b-965d-54155cf855d7)

**Comment by Luna5ama** [comment]
Get better VPN.

**Comment by HenryXiaoYang** [comment]
> Get better VPN.

你那个https://maven.fastmc.dev/有问题的,我都是手动从github下,手动放缓存里才行
然后dev.luna5ama.jar-optimizer在下面repo中4个源都没有,我丢进缓存也没用

可否发一下.m2文件夹? 这样就可以用mavenLocal()直接build了,免去了插件下载

**Comment by HenryXiaoYang** [comment]
然后你可以直接build是因为这几个插件已经在.m2缓存里了 gradle直接用缓存 跳过了下载
