### ISSUE TITLE
I cant send chat

### ISSUE THREAD

**Issue by Most-fat-dog** [Luna5ama/TrollHack#122]
I cant send chat and command.
because I use trollhack.(When I dont use trollhack,I can send chat and command.)

**Comment by Luna5ama** [comment]
what other mods you using?

**Comment by Aspect-404** [comment]
it might be the message queue config, be sure to check Client > Chat Setting > Message Delay

**Comment by Most-fat-dog** [comment]
ok thankyou.


2023年7月9日(日) 16:55 Aspect404_ ***@***.***>:
