### ISSUE TITLE
Gradle构建无法下载插件导致构建失败

### ISSUE THREAD

**Issue by HenryXiaoYang** [Luna5ama/TrollHack#123]
用了vpn 港澳台美日这几个地方节点没一个行的

你那个 https://maven.fastmc.dev/ 有问题的,我都是手动从github下,手动放缓存里才行
然后dev.luna5ama.jar-optimizer在下面repo中4个源都没有,我丢进缓存也没用

可否发一下.m2文件夹? 这样就可以用mavenLocal()直接build了,免去了插件下载

然后你可以直接build是因为这几个插件已经在.m2缓存里了 gradle直接用缓存 跳过了下载

**Comment by okBenito** [comment]
I have the same issue haven't been able to find a work around.

**Comment by GRIFFiin** [comment]
https://windscribe.com

**Comment by Luna5ama** [comment]
> I have the same issue haven't been able to find a work around. Edit: This is actually a non-issue, I was building with java 8, but 17 is required everything works fine.

Yes, Java 17 is required.
