### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Zane2b2t** [Luna5ama/TrollHack#124]
[latest.log](https://github.com/Luna5ama/TrollHack/files/11994872/latest.log)

**Comment by Luna5ama** [comment]
Your GPU is outdated and unsupported. Get a new GPU.

**Comment by Zane2b2t** [comment]
> Your GPU is outdated and unsupported. Get a new GPU.

Now that you've added system requirements to the readme i wanna tell u that im above the requirements (Geforce 840 12gb ram and intel core i7)

**Comment by Luna5ama** [comment]
Update your GPU driver and make sure you are using the dedicated GPU not the integrated GPU from the CPU to run the game.
