### ISSUE TITLE
texture issue

### ISSUE THREAD

**Issue by Most-fat-dog** [Luna5ama/TrollHack#126]
Im used all versions trollhack,but it issues doesnt improvement.
![2023-07-17_09 39 27](https://github.com/Luna5ama/TrollHack/assets/138348867/faefc9c8-0c23-470c-abcf-99adac7bab9f)
(If you cant look this picture,Im sorry.)
minecraft all texture color gits white.
(shader issue?)

**Comment by Luna5ama** [comment]
You have like 69420 clients and they conflict with each other. This isn't a Troll Hack problem but rather the problem of one of your installed clients.

**Comment by Most-fat-dog** [comment]
uwu,when I use troll hack,happen this bug.
