### ISSUE TITLE
AutoFish配置

### ISSUE THREAD

**Issue by xiaomuahua666** [Luna5ama/TrollHack#129]
你好作者，您能教我如何调AutoFish在hypixel的钓鱼任务以及pvp中进行自动掉鱼或掉对方吗。我尝试默认配置完成钓鱼任务，troll一直在操控甩钩，从来不等待是否钓上鱼。而不理解AutoFish的使用方法，不会调配置，能否得到作者的指点

**Comment by Luna5ama** [comment]
检测模式改一下

**Comment by xiaomuahua666** [comment]
细说说？麻烦了！
![image](https://github.com/Luna5ama/TrollHack/assets/109423710/551cd214-cd20-4db4-9dcb-5076f65bf78d)

**Comment by xiaomuahua666** [comment]
可能troll是专为1.12.2写的，所以原配在单人里可以钓鱼，但在1.8的hyp里会一直执行收杆放杆 若无法解决我就手动挂机吧（
