### ISSUE TITLE
how did you make the animation in crystal aura so smooth?

### ISSUE THREAD

**Issue by kisman2000** [Luna5ama/TrollHack#14]

**Comment by Luna5ama** [comment]
Interpolating the position/scaling/alpha with non-linear function
```
val multiplier = Easing.OUT_QUART.inc(Easing.toDelta(lastUpdateTime, movingLength))
val renderPos = prevPos.add(currentPos.subtract(prevPos).scale(multiplier.toDouble()))
scale = if (placeInfo != null) {
    Easing.OUT_CUBIC.inc(Easing.toDelta(startTime, fadeLength))
} else {
    Easing.IN_CUBIC.dec(Easing.toDelta(startTime, fadeLength))
}
```

**Comment by kisman2000** [comment]
thanks, i think troll hack is one of the best hacks for cube game

**Comment by master7720** [comment]
> 

downside it has alot of bloat :( and a kamiblue/lambda skid but still trollhack is still very good

**Comment by master7720** [comment]
> > 
> 
> downside it has alot of bloat :( and a kamiblue/lambda skid but still trollhack is very good

**Comment by kisman2000** [comment]
> Interpolating the position/scaling/alpha with non-linear function
> 
> ```
> val multiplier = Easing.OUT_QUART.inc(Easing.toDelta(lastUpdateTime, movingLength))
> val renderPos = prevPos.add(currentPos.subtract(prevPos).scale(multiplier.toDouble()))
> scale = if (placeInfo != null) {
>     Easing.OUT_CUBIC.inc(Easing.toDelta(startTime, fadeLength))
> } else {
>     Easing.IN_CUBIC.dec(Easing.toDelta(startTime, fadeLength))
> }
> ```

i havent scale method in BlockPos because my forge gradle version is 2.3-SNAPSHOT?

**Comment by Luna5ama** [comment]
> > 
> 
> downside it has alot of bloat :( and a kamiblue/lambda skid but still trollhack is still very good

Better than haveing 69420 clients running together :trollface:

**Comment by kisman2000** [comment]
> > > 
> > 
> > 
> > downside it has alot of bloat :( and a kamiblue/lambda skid but still trollhack is still very good
> 
> Better than haveing 69420 clients running together :trollface:

yes xd

**Comment by master7720** [comment]
> > > 
> > 
> > 
> > downside it has alot of bloat :( and a kamiblue/lambda skid but still trollhack is still very good
> 
> Better than haveing 69420 clients running together :trollface:

another download that either version 0.0.1 or 0.0.2 had a backdoor in it (i have no proof of it but ppl told be that trollhack does have a backdoor in it)

**Comment by kisman2000** [comment]
> > > > 
> > > 
> > > 
> > > downside it has alot of bloat :( and a kamiblue/lambda skid but still trollhack is still very good
> > 
> > 
> > Better than haveing 69420 clients running together :trollface:
> 
> another downside is that either version 0.0.1 or 0.0.2 had a backdoor in it (i have no proof of it but ppl told be that trollhack does have a backdoor in it)

no

**Comment by master7720** [comment]
> > > > > 
> > > > 
> > > > 
> > > > downside it has alot of bloat :( and a kamiblue/lambda skid but still trollhack is still very good
> > > 
> > > 
> > > Better than haveing 69420 clients running together :trollface:
> > 
> > 
> > another downside is that either version 0.0.1 or 0.0.2 had a backdoor in it (i have no proof of it but ppl told be that trollhack does have a backdoor in it)
> 
> no

idk theres been sum jars called "trollhack clean"

**Comment by Luna5ama** [comment]
Ghost backdoor

**Comment by kisman2000** [comment]
?

**Comment by TwoThreeTwo** [comment]
epsilon rat in trollhack 😱
