### ISSUE TITLE
May I use your src?

### ISSUE THREAD

**Issue by pvc03** [Luna5ama/TrollHack#18]
May I use your Trollhack to make my own hack and publish it for free.
I will indicate the original author.

**Comment by TwoThreeTwo** [comment]
There is no license so you don't really have to provide credits but do it anyway. Don't recommend skidding though, very bad :(

**Comment by pvc03** [comment]
I think it is necessary to respect the xiaro , plus my question is who you are

**Comment by Luna5ama** [comment]
No skidding, although there is no way I can stop you from doing so.
