### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by 348177282** [Luna5ama/TrollHack#19]
装了会闪退0.0.1就没有问题

**Comment by pvc03** [comment]
路径不要加空格

**Comment by 348177282** [comment]
OK

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月2日 10:56
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [Luna5ama/TrollHack] 问题 (Issue #19)


路径不要加空格

―
