### ISSUE TITLE
Don't know which version of minecraft it is for? and how to open the hack gui? and is it for forge or fabric?

### ISSUE THREAD

**Issue by MaxVerse** [Luna5ama/TrollHack#23]
can you pls answer the above question

**Comment by MaxVerse** [comment]
Here are my questions :-
**1. Which version of minecraft is this hack for?
2. How to open the hack gui?
3. Is it for forge or fabric?**

**Comment by MaxVerse** [comment]
can you pls answer this?

**Comment by ypo-GitHub** [comment]
1:1.12.2
2:press "y"
3:forge
