### ISSUE TITLE
Stuff

### ISSUE THREAD

**Issue by Zane2b2t** [Luna5ama/TrollHack#35]
2b2t setting in noslow doesnt work
Fix zealotcrystal placing obi sometimes instead of crystals
give us the option to disable costum font and main menu as they cannot be disabled
Use the old 0.0.1 or even the private trollhack kamiblue gui as theyre better than 0.0.4
Make notifications disabled by defualt

**Comment by Luna5ama** [comment]
1. dont care about 2b2t
2. stop mixing clients
3. no
4. no
5. no

**Comment by Zane2b2t** [comment]
> 1. dont care about 2b2t
> 2. stop mixing clients
> 3. no
> 4. no
> 5. no

on 2 i was only using trollhack
