### ISSUE TITLE
biggy biggy crash

### ISSUE THREAD

**Issue by xiudeveloper** [Luna5ama/TrollHack#47]
hi
crash log at https://gist.githubusercontent.com/xiudeveloper/f0ca7ee611d60145153694f148ba077c/raw/c5179f55743ee56fda0a1651cac9afba18f531e5/crash%2520log

**Comment by ypo-GitHub** [comment]
Close FastRender

**Comment by xiudeveloper** [comment]
how to close fastrender

**Comment by Luna5ama** [comment]
It is fixed 0.0.5. Just run it with FastRender, it should works.
