### ISSUE TITLE
Trollhack keeps crashing in every version

### ISSUE THREAD

**Issue by HenryXiaoYang** [Luna5ama/TrollHack#52]
Hello, my game keep crashing with trollhack. I checked my forge, it's fine. And I can run the game without the trollhack. The crash report might be helpful. Please fix it, thank you!
[crash-2022-09-19_21.45.24-client.txt](https://github.com/Luna5ama/TrollHack/files/9599480/crash-2022-09-19_21.45.24-client.txt)

**Comment by Luna5ama** [comment]
MacOS is unsupported and will not be fixed since it is an Apple issue.
