### ISSUE TITLE
View jitters in first person, cannot move camera in 3rd person

### ISSUE THREAD

**Issue by iPenguinnn** [Luna5ama/TrollHack#60]
When in first person, my view jitters diagonally, I am using the latest release with the premade release, I didn't compile it myself or alter anything. Other players also appear to be spinning around. I didn't turn any other modules on for this to start happening. 

https://user-images.githubusercontent.com/116741063/198062594-eb30f1a5-d20c-4e7e-ae9d-5416e8e07dd3.mov

**Comment by Luna5ama** [comment]
What other clients are you using?
Did you have ViewLock or KillAura module on?

**Comment by iPenguinnn** [comment]
I didn’t have viewlock on, killaura yes however when I removed trollhack the issue stopped. This was with future rusherhack abyss and 3arthhackk (ik I use a lot of clients lol)

**Comment by Munchax10** [comment]
same happend to me, but i think its fastrender or smth (one of default enabled modules) Disable that, restart game and yea
