### ISSUE TITLE
crashin when 3arth

### ISSUE THREAD

**Issue by Munchax10** [Luna5ama/TrollHack#63]
i have no idea, why crash. I can send logs if needed. Yesterday it was fine, and now its crashing. It isnt a config issue, if i remove 3arth, troll works fine, and when i remove troll, 3arth works fine

**Comment by Munchax10** [comment]
EDIT: its crashes only when joining a world or server (might be render issue)

**Comment by Luna5ama** [comment]
Send log please.

**Comment by Munchax10** [comment]
https://gist.github.com/Munchax10/25671ffa3bb0d3e7a612b849b4cdb42a#file-logs-txt

**Comment by Munchax10** [comment]
i tested trollhack 0.5 and 0.6 and none worked

**Comment by Munchax10** [comment]
Ohhh it might be java cfg issue

**Comment by Munchax10** [comment]
Fixed issue by using java 8 jre, but it still crashes with gs++

**Comment by Luna5ama** [comment]
New log after removing `-Xverify:none` ?

**Comment by Luna5ama** [comment]
Closed due to inactivity
