### ISSUE TITLE
Game freezes every couple of minutes

### ISSUE THREAD

**Issue by GentlemanMC** [Luna5ama/TrollHack#65]
upon playing normally (with no modules enabled)
it will just randomly cause the game to freeze for a good amount of time then becomes normal

**Comment by 06d** [comment]
Can confirm^

**Comment by GentlemanMC** [comment]
was able to track the issue
i think its because of TranslateManager

**Comment by GentlemanMC** [comment]
or autosave

**Comment by GentlemanMC** [comment]
[16:45:46] [Client thread/WARN] [minecraft/Minecraft]: Null returned as 'hitResult', this shouldn't happen! 
this also causes game to freeze

**Comment by GentlemanMC** [comment]
ok i tried all of the above AND disabled customfont -> override vannila and it doesnt freeze anymore

**Comment by Luna5ama** [comment]
> [16:45:46] [Client thread/WARN] [minecraft/Minecraft]: Null returned as 'hitResult', this shouldn't happen!  this also causes game to freeze

That is just bugs with whatever modules modify block selection, just a message no big deal. Will be fixed sometime but not urgent.

**Comment by Luna5ama** [comment]
> ok i tried all of the above AND disabled customfont -> override vannila and it doesnt freeze anymore

It looks like font glyph loading causes the freeze. It happened to me on Intel iGPU. But however, it should be fixed already in [ab63446](https://github.com/Luna5ama/TrollHack/commit/ab63446ad735b607742689526f5eba2f72b8f0cc) https://github.com/Luna5ama/TrollHack/blob/ab63446ad735b607742689526f5eba2f72b8f0cc/src/main/kotlin/me/luna/trollhack/util/graphics/font/GlyphTexture.kt#L32-L33.

What GPU are you using? Are there any new characters like random Unicode chars, Chinese, etc. popping up in your game in any kind of text? (Such as chat messages)

**Comment by GentlemanMC** [comment]
> > ok i tried all of the above AND disabled customfont -> override vannila and it doesnt freeze anymore
> 
> It looks like font glyph loading causes the freeze. It happened to me on Intel iGPU. But however, it should be fixed already in [ab63446](https://github.com/Luna5ama/TrollHack/commit/ab63446ad735b607742689526f5eba2f72b8f0cc)
> 
> https://github.com/Luna5ama/TrollHack/blob/ab63446ad735b607742689526f5eba2f72b8f0cc/src/main/kotlin/me/luna/trollhack/util/graphics/font/GlyphTexture.kt#L32-L33
> 
> .
> What GPU are you using? Are there any new characters like random Unicode chars, Chinese, etc. popping up in your game in any kind of text? (Such as chat messages)

im using a (very very old) amd gpu

**Comment by GentlemanMC** [comment]
and there are is no unicode popping i tested it in singleplayer to be sure

**Comment by Luna5ama** [comment]
Check your F3 to see if the ram usage decreased for some amount right after the freeze

**Comment by GentlemanMC** [comment]
Ight will do when I get on my pc

**Comment by spymansdad** [comment]
how do i fix the issue?

**Comment by Luna5ama** [comment]
I don't have enough information now so I couldn't provide any help.

**Comment by GentlemanMC** [comment]
As I told you it only happens when I have customfont -> override minecraft on

**Comment by Luna5ama** [comment]
Try using this as JVM arguments and see if it gets better
For MultiMC, you have to remove `-Xms2G -Xmx2G ` and put `2048 MB` for min and max memory.

`-Xms2G -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=1 -XX:G1NewSizePercent=2 -XX:G1MaxNewSizePercent=10 -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=10 -XX:G1MixedGCCountTarget=16 -XX:InitiatingHeapOccupancyPercent=50 -XX:G1MixedGCLiveThresholdPercent=50 -XX:G1RSetUpdatingPauseTimePercent=25 -XX:G1OldCSetRegionThresholdPercent=5 -XX:SurvivorRatio=5`

**Comment by GentlemanMC** [comment]
I will try this later and tell you the results 👍
