### ISSUE TITLE
i cant build it

### ISSUE THREAD

**Issue by 8-python-snhk** [Luna5ama/TrollHack#67]
* Where:
Build file 'D:\git\TrollHack\build.gradle.kts' line: 21

* What went wrong:
Plugin [id: 'me.luna.jaroptimizer', version: '1.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'me.luna.jaroptimizer:me.luna.jaroptimizer.gradle.plugin:1.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    maven(https://raw.githubusercontent.com/Luna5ama/JarOptimizer/maven-repo)

why??

**Comment by Auza2008** [comment]
you need iq

**Comment by 8-python-snhk** [comment]
i have iq ok? pls give the lastest maven version

**Comment by Luna5ama** [comment]
Got keked by GFW, get your VPN on.
