### ISSUE TITLE
GUI windows become uninteractive

### ISSUE THREAD

**Issue by dezintgarecja** [Luna5ama/TrollHack#68]
With certain modules, the config windows in ClickGUI become unresponsive after being closed once. They still open but you can't interact with them, e.g. move them around, change the settings, scroll up and down
This happened with ZealotCrystal+ and Speed, didn't happen with NoRender and some others; that's only the ones I tested.

Also when I open the inventory, the background starts twitching back and forth really fast

**Comment by Luna5ama** [comment]
Will do some investigations into this later.
