### ISSUE TITLE
Whats the change log for version 0.0.2

### ISSUE THREAD

**Issue by master7720** [Luna5ama/TrollHack#7]

**Comment by TwoThreeTwo** [comment]
Mixins
More Mixins
More More Mixins
Code Cleanup using IntelliJ Reformat Code -> CleanUp Code
Changed imports from cum.xiaro to me.luna 
More CodeCleanup from IntelliJ

**Comment by master7720** [comment]
> Mixins More Mixins More More Mixins Code Cleanup using IntelliJ Reformat Code -> CleanUp Code Changed imports from cum.xiaro to me.luna More CodeCleanup from IntelliJ New Font for MainMenu Special KeyBinds for MainMenu New GlSl Background for MainMenu MainMenuModifications Some Bug Fixes.

(added backdoor)
