### ISSUE TITLE
删除patcher模组后无法启动游戏

### ISSUE THREAD

**Issue by its-Hans** [Luna5ama/TrollHack#87]
我习惯在minecraft中使用Patcher模组(https://www.sk1er.club/mods/patcher)来提升fps 我发现某些情况下这个模组兼容性很差 当删除此模组以及essential文件夹（这个模组的前置）之后启动器提示我由于troll导致了游戏崩溃 之后即使我复制模组文件夹和配置文件夹到新安装的minecraft版本中也同样崩溃 装上patcher后又能启动了

**Comment by Luna5ama** [comment]
Send log (`.minecraft/logs/debug.log` or `.minecraft/logs/latest.log`)

**Comment by its-Hans** [comment]
很抱歉占用了您的时间 似乎删除surge之后便正常了 同时有一个吃苹果崩溃的bug也一样修复了
