### ISSUE TITLE
Reason to believe troll hack isn’t safe 

### ISSUE THREAD

**Issue by Drcheeto11** [Luna5ama/TrollHack#90]
This post will probably get deleted in 24h, just like the last one. I asked “is troll hack safe?” And a commenter said no, and the post was deleted in 8 hours. o7 im probably just going to build it myself.

**Comment by Luna5ama** [comment]
It is not deleted what do you mean lol. I'm just closing it because it is irrelevant random nonsense. https://github.com/Luna5ama/TrollHack/issues/89
