### ISSUE TITLE
wont setupdecompworkspace

### ISSUE THREAD

**Issue by lafterdothefunny** [Luna5ama/TrollHack#91]
whenever i try to setup the decomp workspace it just errors and says this

FAILURE: Build failed with an exception.

* What went wrong:
Task 'setupdecompworkspace' not found in root project 'TrollHack'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by lafterdothefunny** [comment]
i am using java 1.8.0 jdk and trollhack 0.0.2 as the source

**Comment by Luna5ama** [comment]
There isn't setupdecompworkspace task because TrollHack doesn't use outdate Forge Gradle. Just import Gradle project and you have everything.
