### ISSUE TITLE
crashed and constantly lagging/frame dropping

### ISSUE THREAD

**Issue by oMustang** [Luna5ama/TrollHack#93]
crashed for the first time but there is constant lag/frame drops. using gs++(nexus), future, earth, troll

[latest.log](https://github.com/Luna5ama/TrollHack/files/10830464/latest.log)

**Comment by Luna5ama** [comment]
Probably causes by mixing clients and Future gets trolled. Try without Future AutoTotem.
![image](https://user-images.githubusercontent.com/62033805/221430644-481e7ec9-af0c-4dbf-932d-65a14868890c.png)

**Comment by 0-x-2-2** [comment]
AutoTotem should be fine, check if AutoPot, AutoSoup, AutoFish, ChestAura, ChestStealer, InvCleaner, InventoryInfo, AutoTunnel, and/or Speedmine are enabled.

**Comment by oMustang** [comment]
InventoryInfo and AutoPot were the issue thanks!
