### ISSUE TITLE
fabric or forge to use it?

### ISSUE THREAD

**Issue by frayray909090** [Luna5ama/TrollHack#97]
i want to try it out idk what one to use or what version can you please help me?

**Comment by Smug2f** [comment]
you should use the latest it's in the release section , the client itself is 1.12.2 so you would need forge for it  you can get it here
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.12.2.html 
make sure to dowload the latest forge and not the recommended one to make it work 

Hope That Helped

**Comment by frayray909090** [comment]
yea i was woundering so i know what jdk to compile it with thanks

**Comment by Luna5ama** [comment]
> yea i was woundering so i know what jdk to compile it with thanks
> 

You need to run Gradle with Java 17. But you need to run the client with Java 8. I would update the README.MD with those information later.

**Comment by frayray909090** [comment]
yea i know the version's of jdk to use for each version of mc version

**Comment by frayray909090** [comment]
> > yea i was woundering so i know what jdk to compile it with thanks
> 
> You need to run Gradle with Java 17. But you need to run the client with Java 8. I would update the README.MD with those information later.

@Luna5ama i thought it was a hack :(
thats why i wanted to try it
