### ISSUE TITLE
Crash with earth 

### ISSUE THREAD

**Issue by LxzeTheLinearFemboy** [Luna5ama/TrollHack#98]
Trollhack crashes when using earth with it (earth works perfectly fine on its own)
[latest.log](https://github.com/Luna5ama/TrollHack/files/11196546/latest.log)

**Comment by Smug2f** [comment]
Earth 1.8.6+ crash when using with troll , try the 1.8.5 ver or the 1.6.2 it should work much better than the 1.8.6+ version

**Comment by Luna5ama** [comment]
Fixed in latest nightly
