### ISSUE TITLE
游戏customfont错误

### ISSUE THREAD

**Issue by rocky-co** [Luna5ama/TrollHack#99]
![image](https://user-images.githubusercontent.com/65335475/232255114-40f7ef46-e6a2-4276-a856-59cd5f6227cd.png)
CustomFont 使得大部分汉字无法查看，游戏内也一样

**Comment by rocky-co** [comment]
版本：0.0.7
Unicode: 开

**Comment by Luna5ama** [comment]
字形没加载好，等一会就好了。

**Comment by rocky-co** [comment]
已解决 谢谢
